language:
-  python
os:
- osx
branches:
  only:
  - master
python:
- "3.6"
before_install:
- sudo apt-get update
- sudo apt-get install python3
#command to install dependencies
install: 
- pip install -r docs/requirements.txt
- pip install .
#command to check spelling
script:
- sphinx-build -b spelling docs/source build
#command to make html docs
script:
- sphinx-build -b spelling docs/source build
