language:
-  python
branches:
  only:
  - master
python:
- "3.6"
#command to install dependencies
install: "pip install -q -r docs/requirements.txt"
#command to check spelling
script:
- sphinx-build -b spelling docs/source build
#command to make html docs
script:
- sphinx-build -b spelling docs/source build
